POST https://suket-mataram-timur-server.vercel.app/register
Content-Type: application/json

{
    "firstName": "admin",
    "lastName": "2",
    "email": "admin2@gmail.com",
    "password": "12345",
    "confPassword": "12345"
} 

###

POST https://suket-mataram-timur-server.vercel.app/login
Content-Type: application/json

{
    "email" : "admin1@gmail.com",
    "password": "12345"
}

###

GET http://localhost:5000/token

###

DELETE http://localhost:5000/logout